title: tonidy.log
description: Tulisan seseorang yang demen sama IT

url: https://www.tonidy.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
# - title: Contact
#   url: /contact.html

social:
   github: tonidy
   twitter: tonidermawan
   facebook: tonidermawan
   email: tonidy@outlook.com

google_analytics: "UA-66024598-1"

theme: jekyll-theme-cayman
