title: tonidy.log
description: catatan cowok yang ngoprek IT dan seputar kehidupannya

url: http://tonidermawan.net/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
# - title: Contact
#   url: /contact.html

social:
   github: tonidy
   twitter: tonidermawan
   facebook: tonidermawan
   email: toni.dy2@gmail.com

google_analytics: "UA-66024598-1"

theme: jekyll-theme-cayman